apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwtSecret | quote }}
  opamp-shared-secret: {{ .Values.opampSharedSecret | quote }}
  db-dsn: {{ .Values.config.dbDSN | quote }}
