{{- if or .Values.jwtSecret .Values.opampSharedSecret .Values.database.dsn }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwtSecret | quote }}
  opamp-shared-secret: {{ .Values.opampSharedSecret | quote }}
  {{- if .Values.database.dsn }}
  db-dsn: {{ .Values.database.dsn | quote }}
  {{- end }}
{{- end }}
